services:

  frontend:
    tty: true
    hostname: frontend.example.com
    environment:
      HOST: 0.0.0.0
    build: .
    ports:
      - "5003:5000"
    volumes:
      - ./:/usr/app/frontend
      - ./src:/usr/app/frontend/src
      - ./src/TokenBat.sol:/usr/app/frontend/src/TokenBat.sol
    command:
      - npm
      - run
      - dev
      - -- host

