
services:

  #-------------------------- compila contratos 
  app: &app
    tty: true
    stdin_open: true
    build:
      context: .
      target: contract
    environment:
      dapk: "8dc139be3c85d64e2420f93eaf7a90d547f2b6fd3ebd0a72d4dce30a1bf4f145"
      NODE_OPTIONS: "--openssl-legacy-provider"
      ETHERSCAN_API_KEY: "EDBKYENP4HQJ3B5QAKJXUMDK245521HN7J"

  #esto requiere conexión a internet para bajar compiladores
  #Despues de bajarlos, se ejecutan algunas tareas
  #
  compile: 
    <<: *app
    #artifacts es importante para nosotros pues necesitamos el código binario
    #para luego hacer deploy en el ganache local
    #usando curl
    #buscar en la carpeta curl ganache-local
    #Esto es porque no funciona hacer deploy a la dirección 0.0.0.0:8545
    #usando el scritps/deploy.js
    #artifacts requiere que sea declarado en hardhat.config.js
    #pues no aparecerán los compilados
    #También hay que colocarlo como mapeo de docker para tener acceso al contenido 
    #Desde fuera de la imagen. De paso que quede grabado en el repositorio
    #module.exports = {
    #olidity: "0.8.9",
    #paths: {
    #rtifacts: './src/artifacts',
    #},
    #etworks: {
    #ardhat: {
    # chainId: 1337
    #}
    #}
    #;

    volumes:
      - ./contract/artifacts:/usr/app/contract/artifacts
    command: "npx hardhat compile --force --verbose"


  #---------------------------------------------
  #
  #
  #-............... ambiente hardhat -----------
  test:
    <<: *app
    command: "npx hardhat test --verbose"

  console:
    <<: *app
    command: "npx hardhat console --verbose"

  node:
    <<: *app
    ports:
      - "8545:8545"
    command: "npx hardhat node"

  deploy:
    <<: *app
    command: "npx hardhat run scripts/deploy.js"


  fund:
    <<: *app
    command: "npx hardhat run scripts/fund_localhost.js"



  #llamar a node en otra pantalla
  #https://hardhat.org/hardhat-runner/docs/getting-started
  #no funciona, dice que se rechaza la conexión
  #Tal vez es un problema de proxies y cosas así.
  #Hay que cerciorarse de que la dirección 8545:8545 esté en 
  #service node: en la key ports
  deply:
    <<: *app
    command: "npx hardhat run scripts/deploy.js --network bocaciega"

  #-------------------------------------------------------
  #
  #---- frontend que se usa para mostrar un botón mint ---

  frontend:
    tty: true
    hostname: frontend.example.com
    environment:
      HOST: 0.0.0.0 
    build:
      context: .
      target: frontend
    volumes:
      - ./docs/build:/usr/app/frontend/public/build/
    ports:
      - "5003:5000"
    command:
      - npm
      - run 
      - dev
      - -- host


  #------------- worker de cloudflare que gestiona la imagen del token nft
  #
  #https://hub.docker.com/r/avatarnewyork/wrangler#using-environment-variables       
  worker: &worker
    tty: true
    stdin_open: true
    build:
      context: .
      target: worker
    ports:
      - "9004:9006"
    volumes:
      - ./worker:/usr/app/worker
      - ./worker/.wrangler/config/:/root/.wrangler/config/
    

  #http://0.0.0.0:9004/nft/1
  #en wrangler.toml
  #expeficar la ip y el puerto
  #si necesita combiarlo
  #esto debe coincidier con la línea
  #ports del servicio
  worker-dev:
    <<: *worker
    hostname: nft.alectrico.d
    ports: 
      - "9005:9004"
    volumes:
      - ./worker:/usr/app/worker
      - ./worker/.wrangler/config/:/root/.wrangler/config/
    command:
      - wrangler
      - dev
      - --env=development

  #worker-preview sto abre una IDE para preubas con sede en cloudflare
  #escribir 
  #https://example.com/nft/00000000001.json
  #debe responder con un json
  #{"name":"CFNFT #00000000001.json","description":"CFNFT #00000000001.json","image":"https://cloudflare-ipfs.com/ipfs/Qma6eRuWT27UyCZCCVNpnndzRYWqyQrX4DfdgMCsLs5u8H"}
  worker-preview:
    <<: *worker
    tty: true
    volumes:
      - ./worker:/usr/app/worker
      - ./worker/.wrangler/config/:/root/.wrangler/config/
    ports:
      - "9008:9004"
    command:
      - wrangler
      - preview

  worker-publish:
    <<: *worker
    volumes:
      - ./worker:/usr/app/worker
      - ./worker/.wrangler/config/:/root/.wrangler/config/
    ports:
      - "9007:9004"
    command:
      - wrangler
      - publish

  #No de me deja ingresar comandoso como en un shell
  #Hay que crear una config usando wrangler config
 
  #config path does not exist /root/.wrangler/config/default.toml.
  worker-console:
    <<: *worker
    tty: true
    stdin_open: true
    volumes:
     - ./worker:/usr/app/worker/
    ports:
      - "9006:9004"
    command:
      - wrangler
      - config
      - -c wrangler.toml
      
  #-----------------------------------------




