volumes:
  node_modules:

services:

  app: &app
    tty: true
    stdin_open: true
    build: . 
    environment:
      dapk: "8312700601314f76129d91130b5e9a29b3345a21129a5748b849da51a0934325"
      NODE_OPTIONS: "--openssl-legacy-provider"
      ETHERSCAN_API_KEY: "EDBKYENP4HQJ3B5QAKJXUMDK245521HN7J"
    volumes:
      - ./scripts:/usr/app/contract/scripts
      - ./contracts:/usr/app/contract/contracts
      - ./artifacts:/usr/app/contract/artifacts
      - ./root/.cache/hardhat-nodejs/compilers/linux-amd64:/root/.cache/hardhat-nodejs/compilers/linux-amd64/
      - ./test:/usr/app/contract/test
      - ./:/usr/app/contract
      - node_modules:/usr/app/contract/node_modules
     
  compile:
    <<: *app
    command: npx hardhat compile --verbose
    depends_on: 
      - app


  nodo:
    <<: *app
    tty: true
    stdin_open: true
    environment:
      dapk: "8312700601314f76129d91130b5e9a29b3345a21129a5748b849da51a0934325"
    ports:
      - "8545:8545"
    command: 
      - npx
      - hardhat
      - node


