global_api = "0cedbd8ae7baab66c24fc2bb7f7f9d2c2d93d"
api_token = "T8v409YMVPEdL-_1qMzyK-WRyYeeYzwzDtWQJTaU"

zone_id = "7a664e9f6d9a9038d40f3e15529ead04"

route = { pattern = "nft.alectrico.cl/nft/*", zone_id = "7a664e9f6d9a9038d40f3e15529ead04" } 

name = "nft"
type = "javascript"
compatibility_date = "2022-05-13"
main= "build/output.js"
#este es el id de la cuenta alectrico.cl
account_id = "e9bc21da719562a3e45d77de7dd042de"
workers_dev = true


[dev]
ip="0.0.0.0"
port="9004"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"


